#+begin_src latex
  \section*{Introduction}
  The Neighbors package provides tools for finding the target and
  neighbor genomes used to find regions that are ubiquitous in the
  targets and absent from the neighbors. These target regions are a good
  starting point for constructing diagnostic markers. In this Tutorial I
  demonstrate the application of the seven programs in the Neighbors
  package in the context of marker discovery. We begin by constructing a
  local relational database from the NCBI taxonomy using the program
  \ty{makeNeiDb}. Then we query the database with \ty{taxid} to find the
  taxon-ID for our target organism. The programs \ty{ants} and \ty{dree}
  allow us to explore the taxonomic context of our target
  organism. Based on the target taxon-ID, we carry out the search for
  target and neighbor genomes using \ty{neighbors}.

  Any genomes suggested by \ty{neighbors} are best subjected to
  phylogeny reconstruction before we extract marker candidates from
  them. The prerequisite phylogeny reconstruction is supported by two
  additional programs from the Neighbors package, \ty{land} for labeling
  the nodes in a phylogeny, and \ty{pickle} for picking a particular
  clade in a phylogeny. Actual marker discovery is done with \ty{fur}\footnote{\ty{https://github.com/evolbioinf/fur}}.

  \section*{Construct Database}
  A dump of the current NCBI taxonomy database is posted as a tar ball at
  \begin{verbatim}
  ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
  \end{verbatim}
  The corresponding genome reports for prokaryotes, eukaryotes, and
  viruses are posted at
  \begin{verbatim}
  ftp.ncbi.nlm.nih.gov/genomes/GENOME_REPORTS/prokaryotes.txt
  ftp.ncbi.nlm.nih.gov/genomes/GENOME_REPORTS/eukaryotes.txt
  ftp.ncbi.nlm.nih.gov/genomes/GENOME_REPORTS/viruses.txt
  \end{verbatim}
#+end_src
#+begin_src latex
  The database dump and the genome reports are updated regularly. To
  ensure the stability of this Tutorial, we use files downloaded on
  14. September 2022:
#+end_src
#+begin_src sh <<db.sh>>=
  wget guanine.evolbio.mpg.de/neighbors/neidb.tgz
#+end_src
#+begin_src latex
  We unpack the database files, delete the tar file, change into the new
  directory \ty{neidb}, and unpack the database dump.
#+end_src
#+begin_src sh <<db.sh>>=
  tar -xvzf neidb.tgz
  rm neidb.tgz
  cd neidb
  tar -xvzf taxdump.tar.gz
#+end_src
#+begin_src latex
  We can now construct the taxonomy database, \ty{neidb}, using
  \ty{makeNeiDb}. This takes approximately 17s. Then we return to the
  parent directory and move the database \ty{neidb} there. Since the
  database has the same name as the directory that contains it, we first
  move the database to \ty{tmpdb}, remove the download directory, and
  move \ty{tmpdb} to \ty{neidb}.
#+end_src
#+begin_src sh <<db.sh>>=
  makeNeiDb
  cd ../
  mv neidb/neidb tmpdb
  rm -r neidb
  mv tmpdb neidb
#+end_src
#+begin_src latex
  \section*{Query Database}
  The next step is to find the taxon-IDs for one or more target
  organisms. Our target organism is the bactrium \emph{Escherichia coli}
  O157:H7, which can cause severe diarrhea in humans. We look up its
  taxon-ID using \ty{taxi} in substring mode (\ty{-s}). For each taxon
  we get the ID, the parent ID, and the name.
#+end_src
#+begin_src sh <<query.sh>>=
  taxi -s "O157:H7" neidb | head
#+end_src
#+begin_src latex
  \begin{verbatim}
  # ID       Parent  Name
    1282359  83334   Escherichia coli O157:H7 str. EC1825
    1446652  83334   Escherichia coli O157:H7 str. F6142
    996639   83334   Escherichia coli O157:H7 str. EC10
  ...
  \end{verbatim}
  Our \ty{taxi} query returns 137 distinct taxa.
#+end_src
#+begin_src sh <<query.sh>>=
  taxi -s "O157:H7" neidb |
      tail -n +2 |
      wc -l
#+end_src
#+begin_export latex
In order to find out the taxon that summarizes all O157:H7 strains, we
sort and count the parent taxa to find that 136 of our 137 taxa have
parent 83334, which in turn has parent 562.
#+end_export
#+begin_src sh <<query.sh>>=
  taxi -s O157:H7 neidb |
      tail -n +2 |
      awk '{print $2}' |
      sort |
      uniq -c
#+end_src
#+begin_export latex
\begin{verbatim}
      1 562
    136 83334
\end{verbatim}
We can use \ty{dree} to visualize the taxonomic tree rooted on taxon
83334. The output of \ty{dree} is in dot notation, which can be
rendered into the tree shown in Figure~\ref{fig:ec1} using the program
\ty{dot} from the graphviz package. Figure~\ref{fig:ec1} is too
cramped for reading, but we can see that the tree has only two levels
and that most of its nodes are colored, which means they are linked to
genome sequences.
\begin{figure}
  \begin{center}
    \resizebox{!}{0.9\textheight}{\includegraphics{../tutorial/ec1.ps}}
  \end{center}
\caption{The taxonomic tree of \emph{E. coli} O157:H7 drawn with
  \ty{dree}; taxa with sequenced genomes are shown in color.}\label{fig:ec1}
\end{figure}
#+end_export
#+begin_src sh <<query.sh>>=
  dree 83334 neidb
#+end_src
#+begin_export latex
#+end_export

#+begin_export latex
We saw previously that the parent of 83334 is taxon 562. To find out
its identity, we use \ty{ants} to print the ancestors of 83334. It
turns out that taxon 562 is the species \emph{E. coli}.
#+end_export
#+begin_src sh <<query.sh>>=
  ants 83334 neidb
#+end_src
#+begin_src latex
  \begin{verbatim}
  # Back  ID      Name                      Rank
    9     1       root                      no rank
    8     131567  cellular organisms        no rank
    7     2       Bacteria                  superkingdom
    6     1224    Proteobacteria            phylum
    5     1236    Gammaproteobacteria       class
    4     91347   Enterobacterales          order
    3     543     Enterobacteriaceae        family
    2     561     Escherichia               genus
    1     562     Escherichia coli          species
    0     83334   Escherichia coli O157:H7  serotype
  \end{verbatim}
#+end_src
#+begin_export latex
In the tree returned by \ty{dree}, the number of genomes per node is
reduced to presence/absence. To get the distribution of genomes across
a subtree, we can list its nodes.
#+end_export
#+begin_src sh <<query.sh>>=
  dree -l 83334 neidb | head
#+end_src
#+begin_src latex
  \begin{verbatim}
  # Taxid  Rank      Genomes
  83334    serotype  181
  1282359  strain    1
  1446652  strain    1
  996639   strain    1
  410290   strain    0
  ...
  \end{verbatim}
  We add taxon names to the list.
#+end_src
#+begin_src sh <<query.sh>>=
  dree -l -n 83334 neidb | head
#+end_src
#+begin_export latex
\begin{verbatim}
# Taxid  Rank      Genomes  Name
83334    serotype  181      Escherichia coli O157:H7
1282359  strain    1        Escherichia coli O157:H7 str. EC1825
1446652  strain    1        Escherichia coli O157:H7 str. F6142
996639   strain    1        Escherichia coli O157:H7 str. EC10
410290   strain    0        Escherichia coli O157:H7 str. ...
...
\end{verbatim}
#+end_export
#+begin_export latex
There are 318 genomes for serotype O157:H7.
#+end_export
#+begin_src sh <<query.sh>>=
  dree -n -l 83334 neidb |
      tail -n +2 |
      awk '{s+=$3}END{print s}'
#+end_src
#+begin_export latex
We can reverse-sort the taxon list by the number of genomes to see
that it ranges from 181 to 0.
#+end_export
#+begin_src sh <<query.sh>>=
  dree -n -l 83334 neidb |
      tail -n +2 |
      sort -k 3 -n -r
#+end_src
#+begin_export latex
\begin{verbatim}
83334    serotype  181      Escherichia coli O157:H7
155864   strain    5        Escherichia coli O157:H7 str. EDL933
1343836  strain    2        Escherichia coli O157:H7 str. F8092B
1286877  strain    2        Escherichia coli O157:H7 str. TW14313
997825   strain    1        Escherichia coli O157:H7 str. 1125
...
1240385  strain    1        Escherichia coli O157:H7 str. ...
991907   strain    0        Escherichia coli O157:H7 str. 262
991906   strain    0        Escherichia coli O157:H7 str. 611
886670   strain    0        Escherichia coli O157:H7 str. ZAP430
410290   strain    0        Escherichia coli O157:H7 str. ...
1046240  strain    0        Escherichia coli O157:H7 str. 121
\end{verbatim}
#+end_export
#+begin_export latex
Now we search for the neighbors of O157:H7 using \ty{neighbors}. We
restrict the output from \ty{neighbors} to taxa with genome sequences.
#+end_export
#+begin_src sh <<query.sh>>=
  printf 83334 | neighbors -g neidb
#+end_src
#+begin_src latex
  \begin{verbatim}
  # MRCA(targets): 83334, Escherichia coli O157:H7
  # MRCA(targets+neighbors): 562, Escherichia coli
  # Type  Taxon-ID  Name                         Genomes
  t       83334     E. coli O157:H7              GCA_001695515.1|...
  tt      155864    E. coli O157:H7 str. EDL933  GCA_000732965.1|...
  tt      386585    E. coli O157:H7 str. Sakai   GCA_000008865.2
  tt      444447    E. coli O157:H7 str. EC4206  GCA_000181735.1
  ...
  n       2874053   E. coli O25:H1               GCA_021398485.1
  \end{verbatim}
  I've slightly edited the output of \ty{neighbors} for clarity. It
  begins with three hashed lines. The first states the most recent
  common ancestor of the targets, \emph{E. coli} O157:H7, with taxon-ID
  83334. The second line states the most recent common ancestor of the
  neighbors \emph{and} the targets, \emph{E. coli}, taxon 562. The third
  line is the header of the subsequent table, which consists of four
  columns, type, taxon-ID, name, and genomes. There are three possible
  types, ``t'' for known target, ``tt'' for new target, and ``n'' for
  neighbor.

  We can check that the \ty{neighbors} output also contains the 318
  target genomes we previously listed with \ty{dree}.
#+end_src
#+begin_src sh <<query.sh>>=
  printf 83334 |
      neighbors -l neidb |
      tail -n +2 |
      grep '^t' |
      wc -l
#+end_src
#+begin_export latex
To download the target and neighbor genomes, we need the genome
accessions. These are a bit difficult to extract from the ``report
view'' of the \ty{neighbors} results. So we use the ``list view''
instead. It consists of two columns, sample (target or neighbor) and
accession.
#+end_export
#+begin_src sh <<query.sh>>=
  printf 83334 | neighbors -l neidb | head
#+end_src
#+begin_export latex
\begin{verbatim}
# Sample  Accession
t         GCA_001695515.1
t         GCA_017165115.1
t         GCA_017165395.1
...
\end{verbatim}
#+end_export
#+begin_export latex
We save the accessions to the file \ty{acc.txt}.
#+end_export
#+begin_src sh <<query.sh>>=
  printf 83334 | neighbors -l neidb > acc.txt
#+end_src
#+begin_export latex
Apart from the 318 target genomes we've already seen, there are a
staggering 3072 neighbor genomes.
#+end_export
#+begin_src sh <<query.sh>>=
  grep -c '^n' acc.txt
#+end_src
#+begin_export latex
To download the sequences, we split the accessions into two files,
\ty{tacc.txt} for the targets and \ty{nacc.txt} for the neighbors.
#+end_export
#+begin_src sh <<query.sh>>=
  grep '^t' acc.txt | awk '{print $2}' > tacc.txt
  grep '^n' acc.txt | awk '{print $2}' > nacc.txt
#+end_src
#+begin_export latex
We use the program \ty{datasets} provided by the NCBI to download
genomes. It is available from the \ty{datasets} web site,
\begin{center}
\ty{https://www.ncbi.nlm.nih.gov/datasets/}  
\end{center}
We restrict our analysis to genomes with assembly-level ``complete''
and exclude genomes flagged as ``atypical''. We download the genomes
in ``dehydrated'' form. We begin with the target genomes, of which
there are 132. This means out of the 318 target genomes across all
assembly levels, only 132 are typical and complete. We save the target
genomes in \ty{tdata.zip}.
#+end_export
#+begin_src sh <<query.sh>>=
  datasets download genome accession \
	   --inputfile tacc.txt \
	   --assembly-level complete \
	   --exclude-atypical \
	   --dehydrated \
	   --filename tdata.zip
#+end_src
#+begin_export latex
We repeat the download for the neighbor genomes, where only 267 out of
the 3072 pass our filter.
#+end_export
#+begin_src sh <<query.sh>>=
  datasets download genome accession \
	   --inputfile nacc.txt \
	   --assembly-level complete \
	   --exclude-atypical \
	   --dehydrated \
	   --filename ndata.zip
#+end_src
#+begin_export latex
The genomes arrive as zipped archives. We unzip the targets into the
directory \ty{tdata}.
#+end_export
#+begin_src sh <<query.sh>>=
  unzip tdata.zip -d tdata
#+end_src
#+begin_export latex
We unzip the neighbors into the directory \ty{ndata}.
#+end_export
#+begin_src sh <<query.sh>>=
  unzip ndata.zip -d ndata
#+end_src
#+begin_export latex
We rehydrate the 132 target genomes.
#+end_export
#+begin_src sh <<query.sh>>=
  datasets rehydrate --directory tdata
#+end_src
#+begin_export latex
We rehydrate the 267 neighbor genomes.
#+end_export
#+begin_src sh <<query.sh>>=
  datasets rehydrate --directory ndata
#+end_src
#+begin_export latex
For easier handling, we move the genomes into a new directory,
\ty{all}. We begin with the targets. To help dividing the data into
true targets and neighbors later, we give target genomes the prefix
\ty{t}.
#+end_export
#+begin_src sh <<query.sh>>=
  mkdir all
  for a in tdata/ncbi_dataset/data/*/*.fna
  do
      b=$(basename $a)
      mv $a all/t$b
  done
#+end_src
#+begin_export latex
We also move the neighbor genomes into the common data pool, only this
time we mark their names with prefix \ty{n}.
#+end_export
#+begin_src sh <<query.sh>>=
  for a in ndata/ncbi_dataset/data/*/*.fna
  do
      b=$(basename $a)
      mv $a all/n$b
  done
#+end_src
#+begin_export latex
We've now got the taxonomic targets and neighbors united in the
directory \ty{all} but distinguishable by their prefix. Our next task
is to extract from this data set the phylogenetic---as opposed to
taxonomic---targets and neighbors. We do this by calculating a
distance-based phylogeny. We calculate the requisite distances using
the program
\ty{phylonium}\footnote{\ty{https://github.com/evolbioinf/phylonium}}
and save them in \ty{o157.dist}.
#+end_export
#+begin_src sh <<query.sh>>=
  phylonium all/* > o157.dist
#+end_src
#+begin_export latex
We calculate the tree from the distances with \ty{nj} and midpoint
root it with \ty{midRoot}. Both programs are part of the the
biobox\footnote{\ty{https://github.com/evolbioinf/biobox}}.
#+end_export
#+begin_src sh <<query.sh>>=
  nj o157.dist | midRoot > o157.nwk
#+end_src
#+begin_export latex
The tree in \ty{o157.nwk} is in the widely-used Newick format and you
can render it with your favorite tree plotting program. One example of
such a program is \ty{plotTree} from the biobox. Its default plot
dimensions are too small for out tree of 399 taxa, so we set the
dimensions to $1200\times 1200$ pixel.
#+end_export
#+begin_src sh <<query.sh>>=
  plotTree -d 1200,1200 o157.nwk
#+end_src
#+begin_export latex
However, even at this magnification the taxon labels are difficult to
read. So we replace the neighbors by a simple \ty{n}, which reveals
that the targets are concentrated in the top part of the tree.
#+end_export
#+begin_src sh <<query.sh>>=
  sed 's/n[^f]*fna/n/g' o157.nwk  |
      plotTree -d 1200,1200
#+end_src
#+begin_export latex
We label the nodes in the tree to address individual clades.
#+end_export
#+begin_src sh <<query.sh>>=
  land o157.nwk |
  sed 's/n[^f]*fna/n/g' |
      plotTree -d 1200,1200
#+end_src
#+begin_export latex
To further explore our tree, let's pick the tree rooted on node 252
and remove the taxon labels altogether, leaving only the labels of the
internal nodes, Figure~\ref{fig:o157}A shows the result.
\begin{figure}
\begin{center}
\begin{tabular}{cc}
\textbf{A} & \textbf{B}\\
\includegraphics{../tutorial/ec2.ps} &
\includegraphics{../tutorial/ec3.ps}
\end{tabular}
\end{center}
\caption{Part of the tree containing target and neighbor genomes of
  \emph{E. coli} O157:H7; only node labels (\textbf{A}), and only target (\emph{t}) and neighbor
  (\emph{n}) labels (\textbf{B}). }\label{fig:o157}
\end{figure}
#+end_export
#+begin_src sh <<query.sh>>=
  land o157.nwk |
      pickle -t 252 |
      sed 's/[nt][^f]*fna/ /g' |
      plotTree -d 1200,1200
#+end_src
#+begin_export latex
We can also just plot the node labels, as shown in
Figure~\ref{fig:o157}B.
#+end_export
#+begin_src sh <<query.sh>>=
  land -p x -s x o157.nwk |
      pickle -t x252x |
      sed -E 's/([nt])[^f]*fna/\1/g;s/x[^x]*x//g' |
      plotTree -d 1200,1200
#+end_src
#+begin_export latex
In Figure~\ref{fig:o157} clade 261 is our target clade, while its
closely related sister clade, 254, is made up of neighbors. The root
of this partial tree, 252, is connected to a singleton branch leading
to a target. Since the distance between this lone putative target and
the many targets in clade 261 is substantial, we reassign the loner as
a neighbor. The phylogeny around our target clade is clarified in the
sketch in Figure~\ref{fig:sketch}.
\begin{figure}
  \begin{center}
    \includegraphics{../tutorial/sketch}
  \end{center}
  \caption{Sketch of the phylogeny in Figure~\ref{fig:o157} to clarify
  the location of targets and neighbors.}\label{fig:sketch}
\end{figure}

We begin our search for markers by splitting our tree into targets,
i. e. the taxa in clade 261, and neighbors, the rest.

To separate the targets, we make a directory, \ty{targets}. Then we
use \ty{pickle} in default mode to list the taxa in the target
clade. For each taxon we create a symbolic link to the original data.
#+end_export
#+begin_src sh <<query.sh>>=
  mkdir targets
  land o157.nwk |
  pickle 261 |
      grep -v '^#' |
      while read a; do
	  ln -s $(pwd)/all/$a $(pwd)/targets/$a
      done
#+end_src
#+begin_export latex
We repeat this for the genomes not in clade 261, which we list by
using the complement option (\ty{-c}) in \ty{pickle}.
#+end_export
#+begin_src sh <<query.sh>>=
  mkdir neighbors
  land o157.nwk |
  pickle -c 261 |
      grep -v '^#' |
      while read a; do
	  ln -s $(pwd)/all/$a $(pwd)/neighbors/$a
      done
#+end_src
#+begin_export latex
In preparation for running \ty{fur}, we make its database with
\ty{makeFurDb}. Since the database is used to compare the targets in
node 261 with the rest of the taxa, we call it \ty{261.db}. This takes
approximately 11 minutes.
#+end_export
#+begin_src sh <<query.sh>>=
  makeFurDb -t targets/ -n neighbors/ -d 261.db
#+end_src
#+begin_export latex
Given the database, we can apply \ty{fur} to it. This takes only 6 s,
but unfortunately all our marker candidates are lost in the second
subtraction step.
#+end_export
#+begin_src sh <<query.sh>>=
  fur -d 261.db
#+end_src
#+begin_export latex
\begin{verbatim}
  Step           Sequences  Length  Ns
  -------------  ---------  ------  --
  Subtraction_1         41   29262   0
  Intersection           7    2750  13
  Subtraction_2          0       0   0
\end{verbatim}

We can make the second subtraction step less sensitive by using
megablast mode instead of the default blastn mode. This returns two
fragments of a combined length of 210 nucleotides.---Not much.
#+end_export
#+begin_src sh <<query.sh>>=
   fur -m -d 261.db/
#+end_src
#+begin_export latex
\begin{verbatim}
  Step           Sequences  Length  Ns
  -------------  ---------  ------  --
  Subtraction_1         41   29262   0
  Intersection           7    2750  13
  Subtraction_2          2     210   0
\end{verbatim}

The question is, can we improve our marker yield? We attempt this by
looking for nested markers. Notice that in Figure~\ref{fig:sketch} the
branch separating node 252 from node 253 is much longer than the
branch separating clades 261 and 254. So we begin our search for
nested markers by looking for markers that distinguish clade 253 from
the rest, and then markers that distinguish clade 261---our
targets---from its sister clade 254 (Figure~\ref{fig:sketch}). We
begin by removing the target symbolic links we generated in the
previous round. Then we set new symbolic links for clade 253.
#+end_export
#+begin_src sh <<query.sh>>=
  rm targets/*
  land o157.nwk |
  pickle 253 |
      grep -v '^#' |
      while read a; do
	  ln -s $(pwd)/all/$a $(pwd)/targets/$a
      done
#+end_src
#+begin_export latex
We repeat for the neighbors, that is, all the taxa not contained in
clade 253.
#+end_export
#+begin_src sh <<query.sh>>=
  rm neighbors/*
  land o157.nwk |
  pickle -c 253 |
      grep -v '^#' |
      while read a; do
	  ln -s $(pwd)/all/$a $(pwd)/neighbors/$a
      done
#+end_src
#+begin_export latex
We run \ty{makeFurDb} on the new combination of targets and neighbors
to create a database for comparing clade 253 to the rest of the taxa,
\ty{253.db}.
#+end_export
#+begin_src sh <<query.sh>>=
  makeFurDb -t targets/ -n neighbors/ -d 253.db
#+end_src
#+begin_export latex
We look for markers of clade 253 and find only a 196 bp region that is
riddled with 67 unknown nucleotides, \ty{N}s.
#+end_export
#+begin_src sh <<query.sh>>=
  fur -d 253.db
#+end_src
#+begin_export latex
\begin{verbatim}
  Step           Sequences  Length   Ns
  -------------  ---------  ------   --
  Subtraction_1        219   80769    0
  Intersection         112   18919  776
  Subtraction_2          1     196   67
...
\end{verbatim}
#+end_export
#+begin_export latex
However, if we switch to the less sensitive megablast mode, we get 3.3
kb, of which half a kb is made up of \ty{N}s.---A reasonable yield,
which we save in file \ty{253.fasta}.
#+end_export
#+begin_src sh <<query.sh>>=
  fur -m -d 253.db/ > 253.fasta
#+end_src
#+begin_export latex
Now we look for markers that distinguish target clade 261 from its
closest relative, clade 254 (Figure~\ref{fig:sketch}). As before, we
first construct the target set.
#+end_export
#+begin_src sh <<query.sh>>=
  rm targets/*
  land o157.nwk |
      pickle 261 |
      grep -v '^#' |
      while read a; do
	  ln -s $(pwd)/all/$a $(pwd)/targets/$a
      done
#+end_src
#+begin_export latex
Similarly, we construct the neighbors as consisting of the taxa in
clade 254.
#+end_export
#+begin_src sh <<query.sh>>=
  rm neighbors/*
  land o157.nwk |
      pickle 254 |
      grep -v '^#' |
      while read a; do
	  ln -s $(pwd)/all/$a $(pwd)/neighbors/$a
      done
#+end_src
#+begin_export latex
We run \ty{makeFurDb} to get a database for comparing targets 261 and
neighbors 254, \ty{261\_254.db}. Since the neighborhood contains only
eight taxa, this run of \ty{makeFurDb} only takes half a minute.
#+end_export
#+begin_src sh <<query.sh>>=
  makeFurDb -t targets/ -n neighbors/ -d 261_254.db
#+end_src
#+begin_export latex
Application of \ty{fur} to our new databaase yields 13.3 kb markers,
of which 4.9 kb are \ty{N}s; again, a substantial amount. We save the
markers in \ty{261\_254.fasta}. The next step would be to construct
PCR primers based on \ty{253.fasta} and \ty{261\_254.fasta}. We would
then test \emph{in silico} the specificity and sensitivity of the pair
of primers in detecting \emph{E. coli} O157:H7. Any primers from the
\emph{in silico} work would ultimately be tested in the lab.
#+end_export
#+begin_src sh <<query.sh>>=
  fur -d 261_254.db/ > 261_254.fasta
#+end_src
#+begin_export latex
\begin{verbatim}
  Step           Sequences  Length    Ns
  -------------  ---------  ------    --
  Subtraction_1        331  255255     0
  Intersection         109   33590   645
  Subtraction_2         15   13279  4863
\end{verbatim}
#+end_export
