#+begin_export latex
\section{\ty{mrca}}
\subsection*{Introduction}
The program \ty{mrca} reads a set of starting nodes in a phylogeny and
finds their most recent common ancestor, the MRCA. During the
computation of the MRCA, the program prints the labels of nodes where
lines of descent coalesce. Figure~\ref{fig:mrca} is an example tree
where the six leaves, or taxa, are labeled $a, b,...,f$, and the five
internal nodes are numbered $1,2,...,5$. Let the three boxed taxa $a$,
$b$, and $c$ be the starting nodes. Their MRCA happens to be the root,
node 1.

We find this MRCA by climbing level-wise from the starting nodes
towards their parents. While doing so, we add the current list of
descendants in square brackets to the parental list. If the original
parental list has at least one element and adding to it changes its
size, a coalescence event has been found.

In our example, the first climb is shown with black arrows. This adds
$a$ to the descendants list of the root, $c$ to the descendants list
of node 3, and $e$ to the descendants list of node 5. The second climb
is shown in blue arrows, which adds $c$ to the descendants list of 2
and $e$ to the descendants list of 4. The third climb is shown in
orange. It adds $c$ to the descendant list of 1, which makes 1 the
MRCA of $a$ and $c$, indicated by the orange circle. It also adds $e$
to the descendants list of node 2, which makes it the MRCA of $c$ and
$e$, again indicated by an orange circle. The fourth and last climb is
shown in red, which makes node 1 the MRCA of the three starting nodes
indicated by the red circle.

In our description, the orange move from node 2 to node 1 preceded the
corresponding move from node 4 to node 2. If this order of execution
is reversed, the correct MRCA is already found in the third climb, at
which point the algorithm would stop.
\begin{figure}[ht]
  \begin{center}
    \input{../mrca/labels}
    \scalebox{0.7}{\includegraphics{../mrca/test}}
    \input{../mrca/arrows}
  \end{center}
  \caption{An example tree for finding the most recent common ancestor
    between taxa $a$, $c$, and $e$ (boxed); the walk towards the most
    recent common ancestor, node 1 in this example, proceeds in four
    phases, black, blue, orange, and red, in that order; nodes where
    lines of descent coalesce are circled; the descendants lists are
    in square brackets, with descendants taking the color of the arrow
    that delivered them.}\label{fig:mrca}
\end{figure}

\subsection*{Implementation}
The central idea of the implementation is to identify nodes by their
IDs. IDs are integers, which we also use as keys to a map that
references the original nodes.

Our outline of \ty{mrca} has hooks for imports, functions, and the
logic of the main function.
\bpr{mrca}{pr:mrca}
#+end_export
#+begin_src go <<mrca.go>>=
  package main

  import (
	  //<<Imports, Pr. \ref{pr:mrca}>>
  )
  //<<Functions, Pr. \ref{pr:mrca}>>
  func main() {
	  //<<Main function, Pr. \ref{pr:mrca}>>
  }
#+end_src
#+begin_export latex
\epr
In the main function we set the name of \ty{mrca}, set the usage,
declare the options, and parse them. Then we compile the regex
specifying the node names and parse the input files containing
phylogenies.
#+end_export
#+begin_src go <<Main function, Pr. \ref{pr:mrca}>>=
  util.SetName("mrca")
  //<<Set usage, Pr. \ref{pr:mrca}>>
  //<<Declare options, Pr. \ref{pr:mrca}>>
  //<<Parse options, Pr. \ref{pr:mrca}>>
  //<<Compile regex, Pr. \ref{pr:mrca}>>
  //<<Parse input files, Pr. \ref{pr:mrca}>>
#+end_src
#+begin_export latex
We import \ty{util}.
#+end_export
#+begin_src go <<Import, Pr. \ref{pr:mrca}>>=
  "github.com/evolbioinf/neighbors/util"
#+end_src
#+begin_export latex
The usage consists of the actual usage message, an explanation of the
purpose of \ty{mrca}, and an example command.
#+end_export
#+begin_src go <<Set usage, Pr. \ref{pr:mrca}>>=
  u := "mrca [-v] regex [foo.nwk]..."
  p := "Calculate the MRCA of nodes matching regex."
  e := "mrca 941322 eco7k.nwk"
  clui.Usage(u, p, e)
#+end_src
#+begin_export latex
We import \ty{clui}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mrca}>>=
  "github.com/evolbioinf/clui"
#+end_src
#+begin_export latex
We declare only one option, the version.
#+end_export
#+begin_src go <<Declare options, Pr. \ref{pr:mrca}>>=
  optV := flag.Bool("v", false, "version")
#+end_src
#+begin_export latex
We import \ty{flag}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mrca}>>=
  "flag"
#+end_src
#+begin_export latex
We parse the options. If the user requested the version, we print the
program information, which includes the version, and exits.
#+end_export
#+begin_src go <<Parse options, Pr. \ref{pr:mrca}>>=
  flag.Parse()
  if *optV {
	  util.PrintInfo("mrca")
  }
#+end_src
#+begin_export latex
The first of the remaining command line arguments is the regex
specifying the nodes. If the user provided one, we compile
it. Otherwise, we exit with a friendly request for starting nodes.
#+end_export
#+begin_src go <<Compile regex, Pr. \ref{pr:mrca}>>=
  args := flag.Args()
  if len(args) == 0 {
	  m := "please provide a regex specifying " +
		  "the starting nodes"
	  log.Fatal(m)
  }
  nodeNames, err := regexp.Compile(args[0])
#+end_src
#+begin_export latex
We import \ty{regexp}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mrca}>>=
  "regexp"
#+end_src
#+begin_export latex
The remaining command line arguments are interpreted as file names,
which are passed to the function \ty{ParseFiles}. This applies the
function \ty{parse} to each file. The function \ty{parse}, in turn,
takes as argument the regular expression specifying the node names.
#+end_export
#+begin_src go <<Parse input files, Pr. \ref{pr:mrca}>>=
  files := args[1:]
  clio.ParseFiles(files, nodeNames)
#+end_src
#+begin_export latex
Inside \ty{parse}, we retrieve the node names and construct a scanner
with which we read the phylogenies contained in the current input. We
analyze each phylogeny in turn.
#+end_export
#+begin_src go <<Functions, Pr. \ref{pr:mrca}>>=
  func parse(r io.Reader, args ..interface{}) {
	  nodeNames := args[0].(*regexp.Regexp)
	  sc := nwk.NewScanner(r)
	  for sc.Scan() {
		  tree := sc.Tree()
		  //<<Analyze tree, Pr. \ref{pr:mrca}>>
	  }
  }
#+end_src
#+begin_export latex
To analyze a tree, we first store its nodes. Then we find the starting
nodes, which we print for the user to see. From these starting nodes
we climb towards the root to find the MRCA.
#+end_export
#+begin_src go <<Analyze tree, Pr. \ref{pr:mrca}>>=
  //<<Store tree nodes, Pr. \ref{pr:mrca}>>
  //<<Find starting nodes, Pr. \ref{pr:mrca}>>
  //<<Print starting nodes, Pr. \ref{pr:mrca}>>
  //<<Find MRCA, Pr. \ref{pr:mrca}>>
#+end_src
#+begin_export latex
We store the tree nodes in a map between node IDs and the node
themselves, \ty{nodes}. To fill this map, we call the function
\ty{storeNodes} on our current tree.
#+end_export
#+begin_src go <<Declare variables, Pr. \ref{pr:mrca}>>=
  nodes := make(map[int]*nwk.Node)
  storeNodes(tree, nodes)
#+end_src
#+begin_export latex
The function \ty{storeNodes} implements a recursive tree traversal,
during which we store each node we encounter.
#+end_export
#+begin_src go <<Functions, Pr. \ref{pr:mrca}>>=
  func storeNodes(v *nwk.Node, nodes map[int]*nwk.Node) {
	  if v == nil {
		  return
	  }
	  nodes[v.Id] = v
	  storeNodes(v.Child)
	  storeNodes(v.Sib)
  }
#+end_src
#+begin_export latex
We iterate over the nodes and store those that match the node
names. If we end up with an empty slice of starting nodes, we exit
with a friendly message.
#+end_export
#+begin_src go <<Find starting nodes, Pr. \ref{pr:mrca}>>
  startNodes := []int{}
  for i, node := range nodes {
	  if nodeNames.MatchString(node.Label) {
		  startNodes = append(startNodes, i)
	  }
  }
  if len(startNodes) == 0 {
	  log.Fatal("couldn't find any nodes matching %s",
		  nodeNames)
  }
#+end_src
#+begin_export latex
We print he starting nodes in a user-friendly message.
#+end_export
#+begin_src go <<Print starting nodes, Pr. \ref{pr:mrca}>>=
  label := nodes[startNodes[0]].Label
  fmt.Printf("# Looking for MRCA among %s", label)
  for i := 1; i < len(startNodes); i++ {
	  label = nodes[i].Label
	  fmt.Printf(", %s", label)
  }
  fmt.Printf("\n")
#+end_src
#+begin_export latex
We import \ty{fmt}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mrca}>>=
  "fmt"
#+end_src
#+begin_export latex
To find the MRCA, we construct the variables we need and then climb
the tree.
#+end_export
#+begin_src go <<Find MRCA, Pr. \ref{pr:mrca}>>=
  //<<Construct variables, Pr. \ref{pr:mrca}>>
  //<<Climb tree, Pr. \ref{pr:mrca}>>
#+end_src
#+begin_export latex
As illustrated in Figure~\ref{fig:mrca}, finding the MRCA requires
repeated rounds of moving up the tree, for which we use a sliced child
IDs and a slice of parent IDs. We initialize the slice of parent IDs
with the starting nodes.
#+end_export
#+begin_src go <<Construct variables, Pr. \ref{pr:mrca}>>=
  var children, parents []int
  for _, startNode := range startNodes {
	  children = append(children, startNode)
  }
#+end_src
#+begin_export latex
Our climb to the MRCA ends when we have found all starting nodes among
the descendants of a given node. So we also need to keep track of the
descendants of the nodes we encounter during our climb. We do this
using a map between a node and its pertinent descendants. The map is
initialized by setting each start node as its own descendant.
#+end_export
#+begin_src go <<Construct variables, Pr. \ref{pr:mrca}>>=
  desc := make(map[int][]int)
  for _, startNode := range startNodes {
	  desc[startNode] = append(desc[startNode],
		  startNode)
  }
#+end_src
#+begin_export latex
We climb the tree until we have found the MRCA. At each iteration of
the climb, we first check, whether the MRCA has been found. Then we
copy the descendants from the children to the parents, compare the
resulting descendants to find coalescence events, and replace the
children by the parents to prepare the next round.
#+end_export
#+begin_src go <<Climb tree, Pr. \ref{pr:mrca}>>=
  for true {
	  //<<Has MRCA been found? Pr. \ref{pr:mrca}>>
	  //<<Copy descendants from children to parents, Pr. \ref{pr:mrca}>>
	  //<<Compare descendants lists, Pr. \ref{pr:mrca}>>
	  //<<Replace children by parents, Pr. \ref{pr:mrca}>>
  }
#+end_src
#+begin_export latex
The child with the same number of descendants as there are starting
nodes is the MRCA.
#+end_export
#+begin_src go <<Has MRCA been found? Pr. \ref{pr:mrca}>>=
  ns := len(startNodes)
  for _, child := range children {
	  nd := len(desc[child])
	  if ns == nd {
		  fmt.Printf("MRCA: %d\n", nodes[child].Label)
		  break
	  }
  }
#+end_src
#+begin_export latex
We iterate over the children and append their descendants to those of
their parents.
#+end_export
#+begin_src go <<Copy descendants from children to parents, Pr. \ref{pr:mrca}>>=
  for _, child := range children {
	  desc[parent] = append(desc[parent],
		  desc[child]...)
  }
#+end_src


<<Compare descendants lists, Pr. \ref{pr:mrca}>>
<<Replace children by parents, Pr. \ref{pr:mrca}>>
 


 repeatedly climb from a set of children to their
parents, which we represent by slices of integers. While climbing the
tree, we keep track of a given node's descendants among the starting
nodes. For this we use a map between a node ID and a slice of node
IDs.




<<Imports, Pr. \ref{pr:mrca}>>
