#+begin_export latex
\section*{Introduction}
The program \ty{mrca} reads a set of starting nodes in a phylogeny and
finds their most recent common ancestor, the MRCA. It also prints the
labels of nodes where lines of descent of the starting nodes
coalesce. Figure~\ref{fig:mrca} is an example tree where the six
leaves, or taxa, are labeled $a, b,...,f$, and the five internal nodes
are numbered $1,2,...,5$. Let the three boxed taxa $a$, $b$, and $c$
be the starting nodes. Their MRCA happens to be the root, node 1.

\begin{figure}
  \begin{center}
    \input{../mrca/labels}
    \includegraphics{../mrca/test}
    \input{../mrca/arrows}
  \end{center}
  \caption{An example tree for finding the most recent common ancestor
    between taxa $a$, $c$, and $e$ (boxed); the walk towards their
    most recent common ancestor, node 1, proceeds in three phases,
    black, blue, and orange, in that order; the descendants lists
    calculated during this walk are in square brackets, with
    descendants taking the color of the arrow that delivered them;
    nodes other than the MRCA where lines of descent coalesce are
    discovered in a second traversal and are circled.}\label{fig:mrca}
\end{figure}

We find this MRCA by climbing level-wise from the starting nodes
towards their parents. While doing so, we add the current list of
descendants in square brackets to the parental list. The descendants
lists of the three starting nodes are initialized to themselves.

The first climb is shown with black arrows. This adds $a$ to the
descendants list of node 1, $c$ to the descendants list of node 3, and
$e$ to the descendants list of node 5. The second climb is shown in
blue arrows, which adds $c$ to the descendants list of 2 and $e$ to
the descendants list of 4. The third climb is shown in orange. It adds
$e$ to the descendant list of node 2 and $(e,c)$ to the descendants list
of node 1. Node 1 now has all starting nodes in its descendants list,
which makes it the MRCA.

The individual coalescence events apart from the MRCA are found in a
second tree traversal. In our example there is just one, the circled
node 2.

\begin{table}
  \caption{Example output of \ty{mrca} consisting of the three
    elements, MRCA line, starting nodes table, and coalescence events
    table.}\label{tab:mrca}
  \begin{center}
    \begin{tabular}{|lrl|}
      \hline
      MRCA & 1 &\\\hline
      \#Type & $n$ & Labels\\
      Start & 3 & $a$ $c$ $e$\\\hline
      \#CA & $n$ & Labels\\
      2 & 2 & $c$ $e$\\\hline
    \end{tabular}
  \end{center}
\end{table}

Table~\ref{tab:mrca} shows the output of \ty{mrca} for our example
data. It consists of three elements, the MRCA line, the table of
starting nodes, and the coalescence table. The MRCA line consists of
the keyword ``MRCA'' followed by the node label of the MRCA. The table
of starting nodes consists of a single line specifying type (start),
number of entries, and labels. The coalescence table consists of all
coalescence events apart from the MRCA. For $n$ starting nodes, this
table has $n-2$ entries, one in our example. Since the labels can be
rather verbose, \ty{mrca} only prints them upon request.

\section*{Implementation}
The central idea of the implementation of \ty{mrca} is to identify
nodes by their IDs. Node IDs are integers, which we also use as keys
to a map that references the original nodes.

Our outline of \ty{mrca} has hooks for imports, functions, and the
logic of the run function.
\bpr{mrca}{pr:mrca}
#+end_export
#+begin_src go <<mrca.go>>=
  package mrca

  import (
	  //<<Imports, Pr. \ref{pr:mrca}>>
  )
  //<<Functions, Pr. \ref{pr:mrca}>>
  func Run() {
	  //<<Run function, Pr. \ref{pr:mrca}>>
  }
#+end_src
#+begin_export latex
\epr In the run function we set the name of \ty{mrca}, set its usage,
declare its options, and parse them. Then we compile the regex
specifying the node names and parse the input files containing the
phylogenies.
#+end_export
#+begin_src go <<Run function, Pr. \ref{pr:mrca}>>=
  util.SetName("mrca")
  //<<Set usage, Pr. \ref{pr:mrca}>>
  //<<Declare options, Pr. \ref{pr:mrca}>>
  //<<Parse options, Pr. \ref{pr:mrca}>>
  //<<Compile regex, Pr. \ref{pr:mrca}>>
  //<<Parse input files, Pr. \ref{pr:mrca}>>
#+end_src
#+begin_export latex
We import \ty{util}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mrca}>>=
  "github.com/evolbioinf/neighbors/util"
#+end_src
#+begin_export latex
The usage consists of the actual usage message, an explanation of the
purpose of \ty{mrca}, and an example command.
#+end_export
#+begin_src go <<Set usage, Pr. \ref{pr:mrca}>>=
  u := "mrca [-v] regex [foo.nwk]..."
  p := "Calculate the MRCA of nodes matching regex."
  e := "mrca 941322 eco7k.nwk"
  clio.Usage(u, p, e)
#+end_src
#+begin_export latex
We import \ty{clio}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mrca}>>=
  "github.com/evolbioinf/clio"
#+end_src
#+begin_export latex
Apart from the version, \ty{-v}, we declare one further option, print
node labels, \ty{-l}.
#+end_export
#+begin_src go <<Declare options, Pr. \ref{pr:mrca}>>=
  optV := flag.Bool("v", false, "version")
  optL := flag.Bool("l", false, "print node labels")
#+end_src
#+begin_export latex
We import \ty{flag}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mrca}>>=
  "flag"
#+end_src
#+begin_export latex
We parse the options. If the user requested the version, we print the
program information, which includes the version.
#+end_export
#+begin_src go <<Parse options, Pr. \ref{pr:mrca}>>=
  flag.Parse()
  if *optV {
	  util.PrintInfo("mrca")
  }
#+end_src
#+begin_export latex
The first of the remaining command line arguments is the regex
specifying the nodes. If the user didn't provided one, we exit with a
friendly request for starting nodes. Otherwise, we compile the regex.
#+end_export
#+begin_src go <<Compile regex, Pr. \ref{pr:mrca}>>=
  args := flag.Args()
  if len(args) == 0 {
	  m := "Please provide a regex specifying " +
		  "the starting nodes."
	  log.Fatal(m)
  }
  nodeNames, err := regexp.Compile(args[0])
  util.Check(err)
#+end_src
#+begin_export latex
We import \ty{regexp}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mrca}>>=
  "regexp"
#+end_src
#+begin_export latex
The remaining command line arguments are interpreted as file names,
which are passed to the function \ty{ParseFiles}. This applies the
function \ty{parse} to each file. The function \ty{parse}, in turn,
takes as argument the regular expression specifying the node names and
the labels option.
#+end_export
#+begin_src go <<Parse input files, Pr. \ref{pr:mrca}>>=
  files := args[1:]
  clio.ParseFiles(files, parse, nodeNames, optL)
#+end_src
#+begin_export latex
Inside \ty{parse}, we retrieve the node names and the labels option.
Then we construct a scanner to read the phylogenies contained in the
current input. We analyze each phylogenetic tree in turn.
#+end_export
#+begin_src go <<Functions, Pr. \ref{pr:mrca}>>=
  func parse(r io.Reader, args ...interface{}) {
	  nodeNames := args[0].(*regexp.Regexp)
	  optL := args[1].(*bool)
	  sc := nwk.NewScanner(r)
	  for sc.Scan() {
		  tree := sc.Tree()
		  //<<Analyze tree, Pr. \ref{pr:mrca}>>
	  }
  }
#+end_src
#+begin_export latex
We import \ty{io} and \ty{nwk}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mrca}>>=
  "io"
  "github.com/evolbioinf/nwk"
#+end_src
#+begin_export latex
To analyze a tree, we first store its nodes. Then we find the starting
nodes. From these starting nodes we climb towards the root to find the
MRCA. Then we print the output.
#+end_export
#+begin_src go <<Analyze tree, Pr. \ref{pr:mrca}>>=
  nodes := make([]*nwk.Node, 0)
  mrca := 0
  //<<Store tree nodes, Pr. \ref{pr:mrca}>>
  //<<Find starting nodes, Pr. \ref{pr:mrca}>>
  //<<Find MRCA, Pr. \ref{pr:mrca}>>
  //<<Print output, Pr. \ref{pr:mrca}>>
#+end_src
#+begin_export latex
We import \ty{fmt}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mrca}>>=
  "fmt"
#+end_src
#+begin_export latex
We store the tree nodes in a slice of nodes using the function
\ty{storeNodes}. then we set the Id of each node to its slice index.
#+end_export
#+begin_src go <<Store tree nodes, Pr. \ref{pr:mrca}>>=
  nodes = storeNodes(tree, nodes)
  for i, node := range nodes {
	  node.Id = i
  }
#+end_src
#+begin_export latex
Nodes are stored in a recursive tree traversal.
#+end_export
#+begin_src go <<Functions, Pr. \ref{pr:mrca}>>=
  func storeNodes(v *nwk.Node, nodes []*nwk.Node) []*nwk.Node {
	  if v == nil {
		  return nodes
	  }
	  nodes = append(nodes, v)
	  nodes = storeNodes(v.Child, nodes)
	  nodes = storeNodes(v.Sib, nodes)
	  return nodes
  }
#+end_src
#+begin_export latex
We iterate over the nodes and store those that match the node names
specified by the user. If we end up with an empty slice of starting
nodes, something went wrong and we exit with a friendly message.
#+end_export
#+begin_src go <<Find starting nodes, Pr. \ref{pr:mrca}>>=
  startNodes := []int{}
  for i, node := range nodes {
	  if nodeNames.MatchString(node.Label) {
		  startNodes = append(startNodes, i)
	  }
  }
  if len(startNodes) == 0 {
	  log.Fatalf("couldn't find any nodes matching %s",
		  nodeNames)
  }
#+end_src
#+begin_export latex
We import \ty{log}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mrca}>>=
  "log"
#+end_src
#+begin_export latex
To find the MRCA, we construct the variables we need and then climb
the tree.
#+end_export
#+begin_src go <<Find MRCA, Pr. \ref{pr:mrca}>>=
  //<<Construct variables, Pr. \ref{pr:mrca}>>
  //<<Climb tree, Pr. \ref{pr:mrca}>>
#+end_src
#+begin_export latex
As illustrated in Figure~\ref{fig:mrca}, finding the MRCA requires
repeated rounds of moving up the tree, for which we use a map of
child IDs and a map of parent IDs. We initialize the map of child
IDs with the starting nodes.
#+end_export
#+begin_src go <<Construct variables, Pr. \ref{pr:mrca}>>=
  children := make(map[int]bool)
  parents := make(map[int]bool)
  for _, startNode := range startNodes {
	  children[startNode] = true
  }
#+end_src
#+begin_export latex
Our climb to the MRCA ends when we have found all starting nodes among
the descendants of a given node. So we also need to keep track of the
descendants of the nodes we encounter during our climb. We do this
using a map between a node and its descendants among the starting
nodes. The map is initialized by setting each starting node as its own
descendant.
#+end_export
#+begin_src go <<Construct variables, Pr. \ref{pr:mrca}>>=
  desc := make(map[int]map[int]bool)
  for _, startNode := range startNodes {
	  desc[startNode] = make(map[int]bool)
	  desc[startNode][startNode] = true
  }
#+end_src
#+begin_export latex
In order to later call coalescence events, we also need to count the
lines of descent that gave rise to them. Here we have to ensure we
count each distinct descendant at most once. We do this using a map of
maps, \ty{count}. It maps node IDs to sets of lines of descent. The
sizes of these sets are the desired counts of the lines of descent. We
initialize the counts of the starting nodes to 1. 
#+end_export
#+begin_src go <<Construct variables, Pr. \ref{pr:mrca}>>=
  counts := make(map[int]map[int]bool)
  for _, startNode := range startNodes {
	  counts[startNode] = make(map[int]bool)
	  counts[startNode][startNode] = true
  }
#+end_src
#+begin_export latex
We climb the tree until we find the MRCA. At each climbing step, we
first check, whether the MRCA has been found. This is done by
comparing the sizes of the current descendants sets to the number of
starting nodes, \ty{ns}. If the MRCA has been found, we break from the
loop. Otherwise, we copy the descendants from the children to the
parents, and replace the children by the parents to prepare the next
round.
#+end_export
#+begin_src go <<Climb tree, Pr. \ref{pr:mrca}>>=
  ns := len(startNodes)
  for true {
	  found := false
	  //<<Has MRCA been found? Pr. \ref{pr:mrca}>>
	  if found {
		  break
	  }
	  //<<Copy descendants from children to parents, Pr. \ref{pr:mrca}>>
	  //<<Replace children by parents, Pr. \ref{pr:mrca}>>
  }
#+end_src
#+begin_export latex
The child with the same number of descendants as there are starting
nodes is the MRCA. If we find it, we report the MRCA and skip the rest
of the search for the MRCA.
#+end_export
#+begin_src go <<Has MRCA been found? Pr. \ref{pr:mrca}>>=
  for child, _ := range children {
	  nd := len(desc[child])
	  if ns == nd {
		  mrca = child
		  found = true
		  break
	  }
  }
#+end_src
#+begin_export latex
For each child, we ask whether it has a parent. If so, we add the
child's descendants to those of its parents and store the parent. We
also count the parent's descendants. 
#+end_export
#+begin_src go <<Copy descendants from children to parents, Pr. \ref{pr:mrca}>>=
  for child, _ := range children {
	  if nodes[child].Parent != nil {
		  parent := nodes[child].Parent.Id
		  //<<Add descendants, Pr. \ref{pr:mrca}>>
		  parents[parent] = true
		  //<<Count parent's decendants, Pr. \ref{pr:mrca}>>
	  }
  }
#+end_src
#+begin_export latex
We still need to add the descendants of the current crop of children
to their parents.
#+end_export
#+begin_src go <<Add descendants, Pr. \ref{pr:mrca}>>=
  if desc[parent] == nil {
	  desc[parent] = make(map[int]bool)
  }
  for d, _ := range desc[child] {
	  desc[parent][d] = true
  }
#+end_src
#+begin_export latex
We make sure the current parent's map of descendants exists and note
the line of descent for the current child.
#+end_export
#+begin_src go <<Count parent's decendants, Pr. \ref{pr:mrca}>>=
  if counts[parent] == nil {
	  counts[parent] = make(map[int]bool)
  }
  counts[parent][child] = true
#+end_src
#+begin_export latex
To climb to the next level of the tree, we replace the children by the
parents. For this we reset the map of children using the function
\ty{reset}, which we still need to write. Then we copy the map of
parents to the map of children, and reset the map of parents. At this
point we are ready to repeat the tree climbing.
#+end_export
#+begin_src go <<Replace children by parents, Pr. \ref{pr:mrca}>>=
  reset(children)
  for parent, _ := range parents {
	  children[parent] = true
  }
  reset(parents)
#+end_src
#+begin_export latex
Inside \ty{reset} we delete each element of the incoming map.
#+end_export
#+begin_src go <<Functions, Pr. \ref{pr:mrca}>>=
  func reset(m map[int]bool) {
	  for k, _ := range m {
		  delete(m, k)
	  }
  }
#+end_src
#+begin_export latex
We have now finished the search for the MRCA and turn to the
output, where we print the three elements sketched in
Table~\ref{tab:mrca}, the MRCA, the table of starting nodes, and the
table of coalescence events.
#+end_export
#+begin_src go <<Print output, Pr. \ref{pr:mrca}>>=
  //<<Print MRCA, Pr. \ref{pr:mrca}>>
  //<<Print starting nodes, Pr. \ref{pr:mrca}>>
  //<<Print coalescence events, Pr. \ref{pr:mrca}>>
#+end_src
#+begin_export latex
We print the MRCA.
#+end_export
#+begin_src go <<Print MRCA, Pr. \ref{pr:mrca}>>=
  fmt.Printf("MRCA %s\n", nodes[mrca].Label)
#+end_src
#+begin_export latex
The table of starting nodes consists of a header and a body.
#+end_export
#+begin_src go <<Print starting nodes, Pr. \ref{pr:mrca}>>=
  //<<Print header of starting nodes, Pr. \ref{pr:mrca}>>
  //<<Print body of starting nodes, Pr. \ref{pr:mrca}>>
#+end_src
#+begin_export latex
The header of the table of starting nodes consists of Type, $n$, and
Lable(s); the labels are optional.
#+end_export
#+begin_src go <<Print header of starting nodes, Pr. \ref{pr:mrca}>>=
  fmt.Printf("#Type\tn")
  if *optL {
	  fmt.Printf("\tLabel")
	  if len(startNodes) > 1 {
		  fmt.Printf("s")
	  }
  }
  fmt.Printf("\n")
#+end_src
#+begin_export latex
The body of the starting nodes table consists of a single line.
#+end_export
#+begin_src go <<Print body of starting nodes, Pr. \ref{pr:mrca}>>=
  fmt.Printf("Start\t%d", len(startNodes))
  if *optL {
	  fmt.Printf("\t%s", nodes[startNodes[0]].Label)
	  for i := 1; i < len(startNodes); i++ {
		  l := nodes[startNodes[i]].Label
		  fmt.Printf(" %s", l)
	  }
  }
  fmt.Printf("\n")
#+end_src
#+begin_export latex
We search for coalescence events. If there are any apart from the
MRCA, we print their header and body.
#+end_export
#+begin_src go <<Print coalescence events, Pr. \ref{pr:mrca}>>=
  foundCA := false
  //<<Search for coalescence events, Pr. \ref{pr:mrca}>>
  if foundCA {
	  //<<Print header of coalescence events, Pr. \ref{pr:mrca}>>
	  //<<Print body of coalescence events, Pr. \ref{pr:mrca}>>
  }
#+end_src
#+begin_export latex
To determine whether there are any coalescence events in out tree, we
iterate over the map of descendants. If a node that isn't the MRCA has
more than one descendant, we have found a coalescence event and break
from the loop.
#+end_export
#+begin_src go <<Search for coalescence events, Pr. \ref{pr:mrca}>>=
  for k, v := range desc {
	  if k != mrca && len(v) > 1 {
		  foundCA = true
		  break
	  }
  }
#+end_src
#+begin_export latex
The header consists of three entries, CA, $n$, and optional labels.
#+end_export
#+begin_src go <<Print header of coalescence events, Pr. \ref{pr:mrca}>>=
  fmt.Printf("#CA\tn")
  if *optL {
	  fmt.Printf("\tLabels")
  }
  fmt.Printf("\n")
#+end_src
#+begin_export latex
To print the coalescence events, we walk from the starting nodes
toward the root. So we initialize the children
again with the starting nodes. Then we iterate until we have only one
child left, the MRCA. Until then we repeatedly look up the parents,
check for coalescence events among them, and replace the children by
the parents. Since we might traverse the same coalescence event more
than once, we keep a list of the ones we've done.
#+end_export
#+begin_src go <<Print body of coalescence events, Pr. \ref{pr:mrca}>>=
  //<<Initialize children, Pr. \ref{pr:mrca}>>
  done := make(map[int]bool)
  for len(children) > 0 {
	  //<<Look up parents, Pr. \ref{pr:mrca}>>
	  //<<Check for coalescence events, Pr. \ref{pr:mrca}>>
	  //<<Replace children by parents, Pr. \ref{pr:mrca}>>
  }
#+end_src
#+begin_export latex
We set the children to the starting nodes.
#+end_export
#+begin_src go <<Initialize children, Pr. \ref{pr:mrca}>>=
  reset(children)
  for _, startNode := range startNodes {
	  children[startNode] = true
  }
#+end_src
#+begin_export latex
We reset the parents and look them up anew.
#+end_export
#+begin_src go <<Look up parents, Pr. \ref{pr:mrca}>>=
  reset(parents)
  for child, _ := range children {
	  if nodes[child].Parent != nil {
		  parent := nodes[child].Parent.Id
		  parents[parent] = true
	  }
  }
#+end_src
#+begin_export latex
We iterate over the parents and print a coalescence event if three
conditions hold, the descendants count is greater than 1, the parent
isn't the MRCA, and it hasn't been reported as a coalescence event
before. In order to get reproducible output, we sort the keys of the
parents map using the function \ty{sortKeys}, which we write in a
moment.
#+end_export
#+begin_src go <<Check for coalescence events, Pr. \ref{pr:mrca}>>=
  keys := sortKeys(parents)
  for _, parent := range keys {
	  if len(counts[parent]) > 1 && parent != mrca &&
		  !done[parent] {
		  //<<Print coalescence, Pr. \ref{pr:mrca}>>
		  done[parent] = true
	  }
  }
#+end_src
#+begin_export latex
Inside \ty{sortKeys} we convert the keys of the incoming map into a
sorted slice.
#+end_export
#+begin_src go <<Functions, Pr. \ref{pr:mrca}>>=
  func sortKeys(m map[int]bool) []int {
	  keys := make([]int, 0)
	  for key, _ := range m {
		  keys = append(keys, key)
	  }
	  sort.Ints(keys)
	  return keys
  }
#+end_src
#+begin_export latex
We import \ty{sort}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:mrca}>>=
  "sort"
#+end_src
#+begin_export latex
We print the parent's label, the number of descendants, and, if
requested, the labels of its descendants, again in fixed order.
#+end_export
#+begin_src go <<Print coalescence, Pr. \ref{pr:mrca}>>=
  fmt.Printf("%s", nodes[parent].Label)
  n := len(desc[parent])
  fmt.Printf("\t%d", n)
  if *optL {
	  keys2 := sortKeys(desc[parent])
	  fmt.Printf("\t%s", nodes[keys2[0]].Label)
	  for i := 1; i < len(keys2); i++ {
		  d := keys2[i]
		  fmt.Printf(" %s", nodes[d].Label)
	  }
  }
  fmt.Printf("\n")
#+end_src
#+begin_export latex
We have finished writing \ty{mrca}, time to test it.
\section*{Testing}
Our code for testing \ty{mrca} has hooks for imports and the testing
logic.
#+end_export
#+begin_src go <<mrca_test.go>>=
  package mrca

  import (
	  //<<Testing imports, Pr. \ref{pr:mrca}>>
	  "testing"
  )
  func TestMrca(t *testing.T) {
	  //<<Testing, Pr. \ref{pr:mrca}>>
  }
#+end_src
#+begin_export latex
We construct a set of tests and iterate over them.
#+end_export
#+begin_src go <<Testing, Pr. \ref{pr:mrca}>>=
  var tests []*exec.Cmd
  //<<Construct tests, Pr. \ref{pr:mrca}>>
  for i, test := range tests {
	  //<<Run test, Pr. \ref{pr:mrca}>>
  }
#+end_src
#+begin_export latex
We import \ty{exec}.
#+end_export
#+begin_src go <<Testing imports, Pr. \ref{pr:mrca}>>=
  "os/exec"
#+end_src
#+begin_export latex
Our first couple of tests run on the tree \ty{test.nwk} shown in
Figure~\ref{fig:mrca}. The first test has starting node $a$.
#+end_export
#+begin_src go <<Construct tests, Pr. \ref{pr:mrca}>>=
  f := "test.nwk"
  p := "./cmd/mrca"
  test := exec.Command(p, "a", f)
  tests = append(tests, test)
#+end_src
#+begin_export latex
The next test starts from $e$ and $f$.
#+end_export
#+begin_src go <<Construct tests, Pr. \ref{pr:mrca}>>=
  test = exec.Command(p, "e|f", f)
  tests = append(tests, test)
#+end_src
#+begin_export latex
Now we recreate the example in Figure~\ref{fig:mrca} and start from
$a, c$, and $e$.
#+end_export
#+begin_src go <<Construct tests, Pr. \ref{pr:mrca}>>=
  test = exec.Command(p, "a|c|e", f)
  tests = append(tests, test)
#+end_src
#+begin_export latex
We repeat the previous command with label printing.
#+end_export
#+begin_src go <<Construct tests, Pr. \ref{pr:mrca}>>=
  test = exec.Command(p, "-l", "a|c|e", f)
  tests = append(tests, test)
#+end_src
#+begin_export latex
Our last test runs on the \emph{Escherichia coli} tree of 7k genomes,
where we look up O25b:H4-ST131, which has taxon ID 941322.
#+end_export
#+begin_src go <<Construct tests, Pr. \ref{pr:mrca}>>=
  f = "../data/eco7k.nwk"
  test = exec.Command(p, "941322", f)
  tests = append(tests, test)
#+end_src
#+begin_export latex
When running a test, we compare the results we get to the results we
want, which are stored in files \ty{r1.txt}, \ty{r2.txt}, and so on.
#+end_export
#+begin_src go <<Run test, Pr. \ref{pr:mrca}>>=
  g, err := test.Output()
  if err != nil {
	  t.Error(err)
  }
  f := "r" + strconv.Itoa(i+1) + ".txt"
  w, err := os.ReadFile(f)
  if err != nil {
	  t.Error(err)
  }
  if !bytes.Equal(g, w) {
	  t.Errorf("%s - get:\n%s\nwant:\n%s\n", f, g, w)
  }
#+end_src
#+begin_export latex
We import \ty{strconv}, \ty{os}, and \ty{bytes}.
#+end_export
#+begin_src go <<Testing imports, Pr. \ref{pr:mrca}>>=
  "strconv"
  "os"
  "bytes"
#+end_src
