#+begin_src latex
  \section{Introduction}
  The package \ty{util} collects utility functions. Its outline provides
  hooks for imports, types, variables, and functions.
  \bpa{util}{pa:util}
#+end_src
#+begin_src go <<util.go>>=
  // Package util provides utility functions for the programs
  // indexNeighbors and neighbors.
  package util

  import (
    //<<Imports, Pa. \ref{pa:util}>>
  )
  //<<Types, Pa. \ref{pa:util}>>
  //<<Variables, Pa. \ref{pa:util}>>
  //<<Functions, Pa. \ref{pa:util}>>
#+end_src
#+begin_src latex
  \epa
  \section{\ty{PrintInfo}}
  !\ty{PrintInfo} prints program information and exits.
#+end_src
#+begin_src go <<Functions, Pa. \ref{pa:util}>>=
  func PrintInfo(program string) {
    author := "EvolBioInf"
    email := "haubold|mourato@evolbio.mpg.de"
    license := "Gnu General Public License, " +
      "https://www.gnu.org/licenses/gpl.html"
    clio.PrintInfo(program, version, date,
      author, email, license)
    os.Exit(0)
  }
#+end_src
#+begin_src latex
  We declare the variables \ty{version} and \ty{date}, which ought to be
  injected at compile time.
#+end_src
#+begin_src go <<Variables, Pa. \ref{pa:util}>>=
  var version, date string
#+end_src
#+begin_src latex
  We import \ty{clio} and \ty{os}.
#+end_src
#+begin_src go <<Imports, Pa. \ref{pa:util}>>=
  "github.com/evolbioinf/clio"
  "os"
#+end_src
#+begin_src latex
  \section{\ty{Open}}
  !\ty{Open} opens a file with error checking.
#+end_src
#+begin_src go <<Functions, Pa. \ref{pa:util}>>=
  func Open(file string) *os.File {
    f, err := os.Open(file)
    if err != nil {
      fmt.Fprintf(os.Stderr, "couldn't open %s\n",
        file)
      os.Exit(1)
    }
    return f
  }
#+end_src
#+begin_src latex
  We import \ty{fmt} and \ty{os}.
#+end_src
#+begin_src go <<Imports, Pa. \ref{pa:util}>>=
  "fmt"
  "os"
#+end_src
#+begin_export latex
\section{\ty{Check}}
!\ty{Check} checks an error and aborts if it isn't nil.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:util}>>=
  func Check(err error) {
    if err != nil {
      log.Fatal(err)
    }
  }
#+end_src
#+begin_export latex
We import \ty{log}.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:util}>>=
  "log"
#+end_src
#+begin_export latex
\section{\ty{SetName}}
!The function \ty{SetName} sets the name of the program.
It stores the name in a global variable and prepares the \ty{log}
package to print that name in the event of an error message.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:util}>>=
  func SetName(n string) {
    name = n
    s := fmt.Sprintf("%s: ", n)
    log.SetPrefix(s)
    log.SetFlags(0)
  }
#+end_src
#+begin_export latex
We declare the global string variable \ty{name}.
#+end_export
#+begin_src go <<Variables, Pa. \ref{pa:util}>>=
  var name string
#+end_src
#+begin_export latex
\section{\ty{Version}}
!The function \ty{Version} prints the version and other information
!about the program and exits.
\ty{Version} simply wraps a call to \ty{PrintInfo}.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:util}>>=
  func Version() {
    PrintInfo(name)
  }
#+end_src
#+begin_src latex
  \section{\ty{LevelMsg}}
  !The function \ty{LevelMsg} prints the user message for the
  !option directing the assembly level.

  We use the given assembly levels stored in the variable
  \ty{assemblyLevels} to construct the user message.
#+end_src
#+begin_src go <<Functions, Pa. \ref{pa:util}>>=
  func LevelMsg() string {
    levels := assemblyLevels
    m := "assembly-level: comma-delimited combination " +
      "of " +	levels[0]
    for i := 1; i < len(levels)-1; i++ {
      m += ", " + levels[i]
    }
    m += ", or " + levels[len(levels)-1]
    m += " (default any)"
    return m
  }
#+end_src
#+begin_export latex
The variable \ty{assemblyLevels} contains the four possible assembly
levels.
#+end_export
#+begin_src go <<Variables, Pa. \ref{pa:util}>>=
  var assemblyLevels = []string{"complete",
    "chromosome",
    "scaffold",
    "contig"}
#+end_src
#+begin_export latex
\section{\ty{Quartiles}}
  !The function \ty{Quartiles} takes as argument a slice of floats and
  !calculates the quartiles, including fences for outlier
  !analysis.

  Inside \ty{Quartiles} function, we first create the variable \ty{q}
  for holding the quartiles. This variable is of type \ty{Quart},
  which we still need to define. Then we sort the incoming data,
  determine the median, the lower quartile, the upper quartile, the
  interquartile range, the inner fences, and the outer fences.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:util}>>=
  func Quartiles(data []float64) *Quart {
    q := new(Quart)
    sort.Float64s(data)
    //<<Determine median, Pa. \ref{pa:util}>>
    //<<Determine lower quartile, Pa. \ref{pa:util}>>
    //<<Determin upper quartile, Pa. \ref{pa:util}>>
    //<<Determine interquartile range, Pa. \ref{pa:util}>>
    //<<Determine inner fences, Pa. \ref{pa:util}>>
    //<<Determine outer fences, Pa. \ref{pa:util}>>
    return q
  }
#+end_src
#+begin_src latex
We import \ty{sort}.
#+end_src
#+begin_src go <<Imports, Pa. \ref{pa:util}>>=
  "sort"
#+end_src
#+begin_export latex
As explained in the description of the program \ty{outliers} in
Section~\ref{sec:out}, outlier analysis generates seven values:
\begin{enumerate}
\item the lower outer fence
\item the inner outer fence
\item the lower quartile
\item the median
\item the upper quartile
\item the upper inner fence
\item the upper outer fence
\end{enumerate}
We store these values in the structure \ty{Quart}.
#+end_export
#+begin_src go <<Types, Pa. \ref{pa:util}>>=
  type Quart struct {
    LowerOuterFence float64
    LowerInnerFence float64
    LowerQuartile   float64
    Median          float64
    UpperQuartile   float64
    UpperInnerFence float64
    UpperOuterFence float64
  }
#+end_src
#+begin_src latex
  The median is the midpoint of the data range. We can also think of it
  as the second quartile point.
#+end_src
#+begin_src go <<Determine median, Pa. \ref{pa:util}>>=
  n := len(data)
  m := (n+1) / 2
  q.Median = data[m-1]
  if n % 2 == 0 {
    q.Median = (q.Median + data[m]) / 2.0
  }
#+end_src
#+begin_src latex
  The lower quartile is the first quarter point of the data range.
#+end_src
#+begin_src go <<Determine lower quartile, Pa. \ref{pa:util}>>=
  exactQ := float64(n+1) * 0.25
  f := math.Floor(exactQ)
  l := int(f)
  x := math.Remainder(exactQ, f)
  q.LowerQuartile = data[l-1] + (data[l]-data[l-1]) * x
#+end_src
#+begin_src latex
We import \ty{math}.
#+end_src
#+begin_src go <<Imports, Pa. \ref{pa:util}>>=
  "math"
#+end_src
#+begin_src latex
  The upper quartile is the third quarter point of the data range.
#+end_src
#+begin_src go <<Determin upper quartile, Pa. \ref{pa:util}>>=
  exactQ = float64(n+1) * 0.75
  f = math.Floor(exactQ)
  l = int(f)
  x = math.Remainder(exactQ, f)
  q.UpperQuartile = data[l-1] + (data[l]-data[l-1]) * x
#+end_src
#+begin_src latex
  The interquartile range, $r$, is the difference between the upper and
  lower quartile.
#+end_src
#+begin_src go <<Determine interquartile range, Pa. \ref{pa:util}>>=
  r := q.UpperQuartile - q.LowerQuartile
#+end_src
#+begin_src latex
  The lower and the upper \emph{inner} fences are $1.5r$ removed from
  their nearest quartile.
#+end_src
#+begin_src go <<Determine inner fences, Pa. \ref{pa:util}>>=
  q.LowerInnerFence = q.LowerQuartile - 1.5 * r
  q.UpperInnerFence = q.UpperQuartile + 1.5 * r
#+end_src
#+begin_src latex
  The lower and upper \emph{outer} fences are $3r$ removed from their
  nearest quartile.
#+end_src
#+begin_src go <<Determine outer fences, Pa. \ref{pa:util}>>=
  q.LowerOuterFence = q.LowerQuartile - 3.0 * r
  q.UpperOuterFence = q.UpperQuartile + 3.0 * r
#+end_src
#+begin_export latex
\section{\ty{SendGetRequest}}
  !The function \ty{SendGetRequest} takes as argument an address as a string
  !and the program's options and extra arguments as string slices. It sends a
  !get request using these values and returns the result.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:util}>>=
  func SendGetRequest(address string, options, extraArgs []string) string {
    //<<Encode query, Pa. \ref{pa:util}>>
    //<<Create \ty{get} request, Pa. \ref{pa:util}>>
    //<<Execute request, Pa. \ref{pa:util}>>
    //<<Parse response, Pa. \ref{pa:util}>>
  }
#+end_src
#+begin_export latex
  There may be multiple slices that need to be encoded for a single request.
  This means we should write a function, which handles this url encoding. We 
  use the exploded parameters for passing slices via the url. This means we
  need to iterate over each slice and add key value pairs. The values need to 
  be encoded. The \ty{net/url} package provides a function for this.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:util}>>=
  func urlEncodeSlice(slc []string, paramName string, hasParam *bool) string {
    var sb strings.Builder
    for _, v := range slc {
      if !(*hasParam) {
        sb.WriteRune('?')
        *hasParam = true
      } else {
        sb.WriteRune('&')
      }
      sb.WriteString(paramName)
        sb.WriteRune('=')
      sb.WriteString(url.QueryEscape(v))
    }
    return sb.String()
  }
#+end_src
#+begin_export latex
  Now all we need to do is call \ty{urlEncodeSlice} for both the options and 
  the extra arguments.
#+end_export
#+begin_src go <<Encode query, Pa. \ref{pa:util}>>=
  hasParam := new(bool)
  qOptions := urlEncodeSlice(options, "options", hasParam)
  qExtraArgs := urlEncodeSlice(extraArgs, "extra", hasParam)
#+end_src
#+begin_export latex
  This requires us to import \ty{net/url} and \ty{strings}.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:util}>>=
  "net/url"
  "strings"
#+end_src
#+begin_export latex
  The \ty{net/http} package provides functions for creating requests.
  There is a \ty{Get} function for creating a get request, but it does
  not allow adding headers. We use \ty{NewRequest} instead and define
  the http verb manually.
#+end_export
#+begin_src go <<Create \ty{get} request, Pa. \ref{pa:util}>>=
  req, err := http.NewRequest(http.MethodGet, address+qOptions+qExtraArgs, nil)
  Check(err)
#+end_src
#+begin_export latex
  Http clients provide methods for invoking requests.
  The \ty{http} package uses a default client for this,
  which is public. We are going to use this client as well.
#+end_export
#+begin_src go <<Execute request, Pa. \ref{pa:util}>>=
  resp, err := http.DefaultClient.Do(req)
  Check(err)
#+end_src
#+begin_export latex
  Using the \ty{http} package requires importing it.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:util}>>=
  "net/http"
#+end_src
#+begin_export latex
  Laslty we parse the response using the \ty{io} package and
  return the data.
#+end_export
#+begin_src go <<Parse response, Pa. \ref{pa:util}>>=
  body, err := io.ReadAll(resp.Body)
  Check(err)
  return string(body)
#+end_src
#+begin_export latex
  Though we still need to import \ty{io}.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:util}>>=
  "io"
#+end_src
#+begin_export latex
\section{\ty{SendPostRequest}}
  !The function \ty{SendPostRequest} takes as argument an address as a string,
  !program options and extra arguments as a slice of strings, as well as files
  !and stdin. It sends a post request using these values and returns the 
  !result.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:util}>>=
  func SendPostRequest(address string, options, extraArgs []string, files []*os.File, stdin *os.File) string {
    //<<Encode query, Pa. \ref{pa:util}>>
    //<<Set \ty{post} form data, Pa. \ref{pa:util}>>
    //<<Create \ty{post} request, Pa. \ref{pa:util}>>
    //<<Write \ty{post} headers, Pa. \ref{pa:util}>>
    //<<Execute request, Pa. \ref{pa:util}>>
    //<<Parse response, Pa. \ref{pa:util}>>
  }
#+end_src
#+begin_export latex
  For setting the post form data we use the \ty{multipart} package.
  First we create a new multipart writer. Then we iterate over all
  the files. We create an entry using the writer for each file
  and copy its content. We close the multipart writer at the end.
#+end_export
#+begin_src go <<Set \ty{post} form data, Pa. \ref{pa:util}>>=
  var b bytes.Buffer
  w := multipart.NewWriter(&b)
  for i, file := range files {
    //<<Create entry in writer, Pa. \ref{pa:util}>>
    //<<Copy content, Pa. \ref{pa:util}>>
  }
  //<<Add stdin to writer, Pa. \ref{pa:util}>>
  w.Close()
#+end_src
#+begin_export latex
  We import \ty{bytes} and \ty{mime/multipart}.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:util}>>=
  "bytes"
  "mime/multipart"
#+end_src
#+begin_export latex
  When creating an entry with the multipart writer, we create a new form file.
  We need to provide a key for the map of files and the name of the file itself.
  The multipart package takes care of creating the file headers and other meta data.
#+end_export
#+begin_src go <<Create entry in writer, Pa. \ref{pa:util}>>=
  fw, err := w.CreateFormFile(strconv.Itoa(i), file.Name())
  Check(err)
#+end_src
#+begin_export latex
  We need the \ty{strconv} package for converting integers into strings.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:util}>>=
  "strconv"
#+end_src
#+begin_export latex
  \ty{io.Copy} allows us to copy the file's content to the filewriter.
#+end_export
#+begin_src go <<Copy content, Pa. \ref{pa:util}>>=
  _, err = io.Copy(fw, file)
  Check(err)
#+end_src
#+begin_export latex
  \ty{stdin} needs a slightly different treatment as it's name might raise
  difficulties.
#+end_export
#+begin_src go <<Add stdin to writer, Pa. \ref{pa:util}>>=
  if stdin != nil {
    fw, err := w.CreateFormFile("stdin", "stdin")
    Check(err)
	  _, err = io.Copy(fw, stdin)
	  Check(err)
  }
#+end_src
#+begin_export latex
  We create \ty{post} request. Adding the query string is the same
  as for the get request. The body
#+end_export
#+begin_src go <<Create \ty{post} request, Pa. \ref{pa:util}>>=
  req, err := http.NewRequest(http.MethodPost, address+qOptions+qExtraArgs, &b)
  Check(err)
#+end_src
#+begin_export latex
  We use the writer to set the correct content type including boundaries.
#+end_export
#+begin_src go <<Write \ty{post} headers, Pa. \ref{pa:util}>>=
  req.Header.Set("Content-Type", w.FormDataContentType())
#+end_src
#+begin_export latex
\section{\ty{RemoveOption}}
  !The function \ty{RemoveOption} takes a slice of strings, interprets it as a
  !a vector of call arguments and removes a specified option. It returns the 
  !resulting slice.
  We need to differentiate two kinds of options. There is the bool option, 
  which is just a single string and there are options with values. If the 
  option is followed by a value, we need to remove that as well.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:util}>>=
  func RemoveOption(args []string, option string, removeValue bool) []string {
    //<<Define options, Pa. \ref{pa:util}>>
    if removeValue {
      //<<Remove option with value, Pa. \ref{pa:util}>>  
    } else {
      //<<Remove option, Pa. \ref{pa:util}>>
    }
    return args
  }
#+end_src
#+begin_export latex
  Options are prefixed by one or two dashes. We need to check for both.
#+end_export
#+begin_src go <<Define options, Pa. \ref{pa:util}>>=
  sOption := "-" + option
  dOption := "--" + option
#+end_src
#+begin_export latex
  When removing an option with value we need to iterate over the arguments,
  back to front, and remove all occurrences of the option plus the following 
  entry.
#+end_export
#+begin_src go <<Remove option with value, Pa. \ref{pa:util}>>=
  for i := len(args)-1; i <= 0; i-- {
    if args[i] == sOption || args[i] == dOption {
			args = append(args[:i], args[i+2:]...)
    }
  }
#+end_src
#+begin_export latex
  Removing an option without a value is simpler. We use the \ty{DeleteFunc} 
  function provided by \ty{slices}
#+end_export
#+begin_src go <<Remove option, Pa. \ref{pa:util}>>=
  args = slices.DeleteFunc(args, func(a string) bool {return a == sOption || a == dOption})
#+end_src
#+begin_export latex
  We import \ty{slices}.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:util}>>=
  "slices"
#+end_src

#+begin_src latex
  We are done with writing the \ty{util} package, time to test it.
  \section{Testing}
  Our testing code for \ty{util} contains hooks for imports and the
  logic of the testing function.
#+end_src
#+begin_src go <<util_test.go>>=
  package util

  import (
    "testing"
    //<<Testing imports, Pa. \ref{pa:util}>>
  )

  func TestUtil(t *testing.T) {
    //<<Testing, Pa. \ref{pa:util}>>
  }
#+end_src
#+begin_src latex
  There are three functions we can sensibly test, \ty{Open},
  \ty{LevelMsg} and \ty{Quartiles}.
#+end_src
#+begin_src go <<Testing, Pa. \ref{pa:util}>>=
  //<<Test \ty{Open}, Pa. \ref{pa:util}>>
  //<<Test \ty{LevelMsg}, Pa. \ref{pa:util}>>
  //<<Test \ty{Quartiles}, Pa. \ref{pa:util}>>
#+end_src
#+begin_src latex
  To test \ty{Open}, we open a test file and read the string ``success''
  from it.
#+end_src
#+begin_src go <<Test \ty{Open}, Pa. \ref{pa:util}>>=
  f := Open("r.txt")
  defer f.Close()
  sc := bufio.NewScanner(f)
  if !sc.Scan() {
    t.Error("scan failed")
  }
  get := sc.Text()
  want := "success"
  if get != want {
    t.Errorf("get:\n%s\nwant:\n%s\n", get, want)
  }
#+end_src
#+begin_src latex
  We import \ty{bufio}.
#+end_src
#+begin_src go <<Testing imports, Pa. \ref{pa:util}>>=
  "bufio"
#+end_src
#+begin_src latex
  To test \ty{LevelMsg}, we check the message returned matches all
  predefined levels.
#+end_src
#+begin_src go <<Test \ty{LevelMsg}, Pa. \ref{pa:util}>>=
  m := "user message does not match level %q"
  msg := LevelMsg()
  for _, level := range assemblyLevels {
    if strings.Index(msg, level) == -1 {
      t.Errorf(m, level)
    }
  }
#+end_src
#+begin_src latex
  We import \ty{strings}.
#+end_src
#+begin_src go <<Testing imports, Pa. \ref{pa:util}>>=
  "strings"
#+end_src
#+begin_export latex
We test the function \ty{Quartiles} on four data points and
compare the results we get to the results we want.
#+end_export
#+begin_src go <<Test \ty{Quartiles}, Pa. \ref{pa:util}>>=
  data := []float64{30, 171, 184, 201}
  q := Quartiles(data)
  wr := []float64{-329.25, -132, 65.25, 177.5,
    196.75, 394, 591.25}
  gr := []float64{q.LowerOuterFence, q.LowerInnerFence,
    q.LowerQuartile, q.Median, q.UpperQuartile,
    q.UpperInnerFence, q.UpperOuterFence}
  //<<Compare results, Pa. \ref{pa:util}>>
#+end_src
#+begin_export latex
If a result we get doesn't match the result we want, we throw an
error.
#+end_export
#+begin_src go <<Compare results, Pa. \ref{pa:util}>>=
  for i, w := range wr {
    if w != gr[i] {
      t.Errorf("want: %f\nget: %f\n",
        w, gr[i])
    }
  }
#+end_src
