#+begin_src latex
  \section*{Introduction}
Several Neighbors programs are based on the Neighbors database, \ty{neidb}.
These programs can work with either a local copy of \ty{neidb} or a remote 
copy. Users can specify the remote \ty{neidb} by choosing among those hosted
on the Neighbors server, \ty{never}. The program \ty{listNeiDbs} lists the
databases available.

  \section*{Implementation}
  The program \ty{listNeiDbs} has hooks for imports and the logic of the main
  function.\bpr{listNeidbs}{pr:lis}
#+end_src
#+begin_src go <<listNeiDbs.go>>=
  package main

  import (
	  //<<Imports, Pr. \ref{pr:lis}>>
  )

  func main() {
	  //<<Main function, Pr. \ref{pr:lis}>>
  }
#+end_src
#+begin_src latex
  \epr In the \ty{main} function we set the name of \ty{listNeiDbs} and its
  usage, declare the options, parse the options, get the databases, and
  print them.
#+end_src
#+begin_src go <<Main function, Pr. \ref{pr:lis}>>=
  util.SetName("listNeiDbs")
  //<<Set usage, Pr. \ref{pr:lis}>>
  //<<Declare options, Pr. \ref{pr:lis}>>
  //<<Parse options, Pr. \ref{pr:lis}>>
  //<<Get databases, Pr. \ref{pr:lis}>>
  //<<Print databases, Pr. \ref{pr:lis}>>
#+end_src
#+begin_export latex
We import \ty{util}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:lis}>>=
  "github.com/evolbioinf/neighbors/util"
#+end_src
#+begin_src latex
  The usage consists of three parts: The actual usage message, an
  explanation of the purpose of \ty{listNeiDbs}, and an example command.
  All of this is rather straight forward, as \ty{listNeiDbs} does not provide
  a whole lot of options.
#+end_src
#+begin_src go <<Set usage, Pr. \ref{pr:lis}>>=
  u := "listNeiDbs [option]"
  p := "Print all of never's available databases."
  e := "listNeiDbs"
  clio.Usage(u, p, e)
#+end_src
#+begin_src latex
  We import \ty{clio}.
#+end_src
#+begin_src go <<Imports, Pr. \ref{pr:lis}>>=
  "github.com/evolbioinf/clio"
#+end_src
#+begin_src latex
  There is just a single option, which is \ty{-v}.
#+end_src
#+begin_src go <<Declare options, Pr. \ref{pr:lis}>>=
  var optV = flag.Bool("v", false, "version")
#+end_src
#+begin_src latex
  We import \ty{flag}.
#+end_src
#+begin_src go <<Imports, Pr. \ref{pr:lis}>>=
  "flag"
#+end_src
#+begin_src latex
  We parse the options and respond to the version option (\ty{-v}), if it is
  provided.
#+end_src
#+begin_src go <<Parse options, Pr. \ref{pr:lis}>>=
  flag.Parse()
  //<<Respond to \ty{-v}, Pr. \ref{pr:lis}>>
#+end_src
#+begin_export latex
If the user asked for the version, we print the program information,
which contains the version.
#+end_export
#+begin_src go <<Respond to \ty{-v}, Pr. \ref{pr:lis}>>=
  if *optV {
	  util.PrintInfo("listNeiDbs")
  }
#+end_src
#+begin_export latex
  The \ty{util} package of Neighbors provides a function, which lets us send a
  \ty{GET} request. We use this to query \ty{never} for its databases.
  \ty{SendGetRequest} takes four arguments, of which only the first, the 
  address suffix, is strictly necessary. Passing \ty{plain\_data} as a 
  miscellaneous argument is not necessary, but reduces parsing complexity.
#+end_export
#+begin_src go <<Get databases, Pr. \ref{pr:lis}>>=
  a := make(map[string]string)
  a["plain_data"] = "true"
  rawRes := util.SendGetRequest("api/v2/databases", nil, nil, a)
#+end_src
#+begin_export latex
  We import \ty{util}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:lis}>>=
  "github.com/evolbioinf/neighbors/util"
#+end_src
#+begin_export latex
  We get the request's result as a json string. When printing it to
  \ty{stdout}, it should be a comma + space delimited string. We use the
  \ty{json} package to unmarshall the string and allow iteration.
#+end_export
#+begin_src go <<Get databases, Pr. \ref{pr:lis}>>=
  var res []string
  json.Unmarshal([]byte(rawRes), &res)
#+end_src
#+begin_export latex
  We import \ty{encoding/json}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:lis}>>=
  "encoding/json"
#+end_src
#+begin_export latex
  Lastly we join the string slice and print the result.
#+end_export
#+begin_src go <<Print databases, Pr. \ref{pr:lis}>>=
  fmt.Println(strings.Join(res, ", "))
#+end_src
#+begin_export latex
  We import \ty{strings} and \ty{fmt}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:lis}>>=
  "strings"
  "fmt"
#+end_src