* Find Clusters with fintac
The aim is to make fintac recognize the phylogenetic *cluster* to
which a given target taxon belongs. We call a node in a phylogeny the
root of a cluster, if the branch lengths in its subtree are short and
the branch to its parent is long. Given a tree with nodes classified
into clusters and non-clusters, fintac looks for the clade with the
highest split score, and from there walks up to the nearest cluster.

So we need a new program, clust, which takes as input the output from
land and appends to the node labels issued by land either _1 or _0 for
cluster/no cluster. This is used by fintac to find cluster-aware
target clades. With just land input, fintac behaves as before.

** Algorithm of clust
- In bottom-up traversal of tree, construct for each node a list of
  the branch lengths in its subtree
- Iterate over each node, v
  - if no outliers in branch lengths of v
    - if addition of branch length to v's parent creates outlier
        v.isClust <- true
    - end if
  - end if
